version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/update-kubeconfig.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/apply-kubernetes-config.sh
      timeout: 60
      runas: ubuntu
