FROM node:18

WORKDIR /app

# Copy the yarn.lock file from the root of the frontend directory
COPY ../yarn.lock ./

# Copy the package.json file from the app directory
COPY app/package.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the app directory
COPY app/ .

# Expose the port the app runs on
EXPOSE 8080

# Start the development server
CMD ["yarn", "start"]
