apiVersion: apps/v1
kind: Deployment
metadata:
  name: openglot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openglot-web
  template:
    metadata:
      labels:
        app: openglot-web
    spec:
      containers:
      - name: openglot-web
        image: {{IMAGE_URI}}
        ports:
        - containerPort: 80
