version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - ls -al
      - npm install
  build:
    commands:
      - npm run build-prod
  post_build:
    commands:
      - aws s3 sync dist/app s3://openglot-web-production/web
